.Dd July 24, 2020
.Dt OCRON 1
.Os
.Sh NAME
.Nm ocron
.Nd cron daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
schedules commands to be run at specified dates and times.
.Sh CONFIGURATION
Configuration is done by editing the
.Pa /etc/crontab
file.
.sp
.Nm
understands all the usual syntax features and common extensions that you've come to expect from a cron daemon:
.Bl -bullet
.It
Both comments and blank lines are allowed.
.It
Rules are of the following form:
.Bl -column "minutes___" "hours___" "month-days___" "months___" "week-days___" "command___"
.It "minutes" Ta "hours" Ta "month-days" Ta "months" Ta "week-days" Ta "command"
.El
.It
In the first 5 fields,
.Sq *
means that the field is unspecified,
.Sq -
can be used for inclusive ranges,
and a
.Sq /
after a
.Sq *
or after a range specifies the duration between executions in that range.
.It
For the months and week-days fields, 3-letter case-insensitive aliases may be used (for example: Jan, JUL, aug).
.It
In the week-days field, 0 and 7 both mean Sunday.
.It
Commands are executed if
.Em either
the month-day
.Em or
the week-day matches the current day.
.It
If a command is still running by the time it should be executed again,
that execution will be skipped and a warning is logged.
.It
You cannot pass text into a command's stdin by escaping it with a percent sign (which is something other cron implementations allow you to do).
However, because all commands are evaluated by a real shell, you can always pipe stdin data to a command from echo or cat.
.It
.Nm
is able to safely reload its crontab file on-the-fly.
To trigger it, you have to raise a SIGHUP signal.
This can for example done by executing:
.Dl kill -s 1 <pid>
.El
.Sh AUTHORS
.An Thomas Oltmann Aq Mt thomas.oltmann.hhg@gmail.com
